version: "2"

services:
  tron-nile-zookeeper:
    container_name: tron-nile-zookeeper
    image: "docker.io/bitnami/zookeeper:3-debian-10"
    ports:
      - "2181:2181"
    restart: always
    volumes:
      - "$PWD/volumes/tron-nile-zookeeper:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT_NUMBER=2181
  tron-nile-kafka:
    container_name: tron-nile-kafka
    image: "docker.io/bitnami/kafka:2-debian-10"
    ports:
      - "9092:9092"
      - "9093:9093"
    restart: always
    volumes:
      - "$PWD/volumes/tron-nile-kafka:/bitnami/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=tron-nile-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://172.17.0.1:9092,EXTERNAL://139.99.121.150:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - tron-nile-zookeeper
  tron-nile-node:
    container_name: tron-nile-node
    # build: https://github.com/SunStake/docker-java-tron.git
    image: "docker.io/sunstake/java-tron"
    environment:
      - NETWORK=nile
      - EVENT_PLUGIN_ENABLED=true
      - EVENT_PLUGIN_KAFKA_SERVER=172.17.0.1:9092
      - EVENT_PLUGIN_BLOCK_TRIGGER_ENABLED=true
    ports:
      - "8090:8090"
      - "8091:8091"
    restart: always
    volumes:
      - "$PWD/volumes/tron-nile-node:/data"
    depends_on:
      - tron-nile-kafka